import { spotifyApi } from "@/lib/spotify";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
    try {
        const { name, tracks } = await request.json();
        const cookieStore = await cookies();
        let accessToken = cookieStore.get("spotify_access_token")?.value;

        // Fallback: Check Authorization header
        if (!accessToken) {
            const authHeader = request.headers.get("Authorization");
            if (authHeader?.startsWith("Bearer ")) {
                accessToken = authHeader.split(" ")[1];
            }
        }

        if (!accessToken) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        spotifyApi.setAccessToken(accessToken);

        // 1. Get User ID
        const me = await spotifyApi.getMe();
        const userId = me.body.id;

        // 2. Create Playlist
        const playlist = await spotifyApi.createPlaylist(name, {
            description: "Generated by Playlister App",
            public: false,
        });

        // 3. Add Tracks
        const trackUris = tracks.map((t: any) => t.uri);
        await spotifyApi.addTracksToPlaylist(playlist.body.id, trackUris);

        return NextResponse.json({
            success: true,
            playlistId: playlist.body.id,
            playlistUrl: playlist.body.external_urls.spotify
        });
    } catch (error) {
        console.error("Error creating playlist:", error);
        return NextResponse.json({ error: "Failed to create playlist" }, { status: 500 });
    }
}
